### ISSUE TITLE
Plugin gatsby-plugin-social9-socialshare is not compatible with your gatsby version 4.4.0

### ISSUE THREAD

**Issue by k-s-morawska** [social9/gatsby-plugin-social9-share#2]
Could you please update plugin to be compatible with Gatsby 4.?.?

**Comment by kunal-saini** [comment]
Hey @k-s-morawska 

thank you for reporting the issue, we have published the [npm package](https://www.npmjs.com/package/gatsby-plugin-social9-socialshare) to support the compatibility with your gatsby version 4.x.x
